improvements

diff --git a/e2e/iks-cluster b/e2e/iks-cluster
--- a/e2e/iks-cluster
+++ b/e2e/iks-cluster
@@ -1016,13 +1016,13 @@ ibmcloud target -r "$IC_REGION"
 
 # Step4: Set API endpoint for ks plugin
 if [[ -n "$E2ETEST_CS_API_EP" ]]; then
-    KS_HOST="$E2ETEST_CS_API_EP"
-elif [[ "$e2e_env" == "stage" || "$e2e_env" == "stage-us-south" ]]; then
-    KS_HOST="https://containers.test.cloud.ibm.com"
-elif [[ "$e2e_env" == "in-che" ]]; then
-    KS_HOST="https://containers.cloud.ibm.com"
+   ibmcloud ks init --host $E2ETEST_CS_API_EP; rc=$?
 else
-    KS_HOST="https://containers.cloud.ibm.com"
+   ibmcloud ks init --host https://containers.cloud.ibm.com; rc=$?
+fi
+if [[ $rc -ne 0 ]]; then
+    echo "ERROR: Failed to initialize KS with API endpoint" >> $E2E_TEST_SETUP
+    exit 1
 fi
 
 if [[ -z "$KS_HOST" ]]; then
@@ -1031,10 +1031,19 @@ if [[ -z "$KS_HOST" ]]; then
 fi
 
 echo "KS endpoint : $KS_HOST"
-ibmcloud ks init --host "$KS_HOST"
+ibmcloud ks init --host "$KS_HOST"; rc=$?
+if [[ $rc -ne 0 ]]; then
+    echo "ERROR: Failed to initialize KS with host $KS_HOST" >> $E2E_TEST_SETUP
+    exit 1
+fi
+
 
 if [[ $IC_PROVIDER == "vpc-gen2" ]] ; then
-   ibmcloud is target --gen 2
+   ibmcloud is target --gen 2; rc=$?
+   if [[ $rc -ne 0 ]]; then
+       echo "ERROR: Failed to set IS target to gen 2" >> $E2E_TEST_SETUP
+       exit 1
+   fi
 fi
 
 ## Delete cluster if --delete flag is passed
