added greenfied region
Signed-off-by: Renuka Singare <renuka.singare@ibm.com>

diff --git a/e2e/iks-cluster b/e2e/iks-cluster
--- a/e2e/iks-cluster
+++ b/e2e/iks-cluster
@@ -845,7 +845,7 @@ set -- "${POSITIONAL[@]}" # restore positional parameters
 if [[ -z "$IC_API_KEY_PROD" && -z "$IC_API_KEY_STAG"  ]]; then echo -e "Error: E2ETEST_API_KEY not set!!!" >> $E2E_TEST_SETUP; exit 1;  fi
 
 E2ETEST_MZ="$e2e_mz"
-if [[ "$e2e_env" != "prod" && "$e2e_env" != "stage" ]]; then
+if [[ "$e2e_env" != "prod" && "$e2e_env" != "stage" && "$e2e_env" != "stage-us-south" ]]; then
 	echo -e "Error: Invalid option \"-e $e2e_env\"!!!" >> $E2E_TEST_SETUP
 	exit 1
 fi
@@ -874,6 +874,10 @@ if [[ "$e2e_env" = "stage" ]]; then
     E2ETEST_IC_API_EP="https://test.cloud.ibm.com"
     [[ -z "$E2ETEST_CS_API_EP" ]] && E2ETEST_CS_API_EP="https://containers.test.cloud.ibm.com"
     E2ETEST_IC_RES_GRP="Default"
+elif [[ "$e2e_env" = "stage-us-south" ]]; then
+    E2ETEST_IC_API_EP="https://test.cloud.ibm.com"
+    [[ -z "$E2ETEST_CS_API_EP" ]] && E2ETEST_CS_API_EP="https://stage-us-south.containers.test.cloud.ibm.com"
+    E2ETEST_IC_RES_GRP="Default"
 else
     E2ETEST_IC_API_EP="https://cloud.ibm.com"
     [[ -z "$E2ETEST_CS_API_EP" ]] && E2ETEST_CS_API_EP="https://containers.cloud.ibm.com"
@@ -892,7 +896,7 @@ fi
 # Login to IBM Cloud
 set +x
 if [[ -z "$E2ETEST_API_KEY" ]]; then
-    if [[ "$e2e_env" = "stage" ]]; then
+    if [[ "$e2e_env" = "stage" || "$e2e_env" = "stage-us-south" ]]; then
         ibmcloud login -a $E2ETEST_IC_API_EP --apikey ${IC_API_KEY_STAG} -r $IC_REGION -g $E2ETEST_IC_RES_GRP; rc=$?
     else
         ibmcloud login -a $E2ETEST_IC_API_EP --apikey ${IC_API_KEY_PROD} -r $IC_REGION -g $E2ETEST_IC_RES_GRP; rc=$?
@@ -908,13 +912,40 @@ if [[ $rc -ne 0 ]]; then
    exit 1
 fi
 IC_REGION="$e2e_ic_region"
+
+# Resolve final region
+if [[ "$e2e_env" == "stage-us-south" ]]; then
+    IC_REGION="us-south-ngdc-test"
+    # Set default test flavor only if not explicitly set
+    WORKER_NODE_FLAVOR="bx3d.4x20"
+else
+    IC_REGION="$e2e_ic_region"
+fi
+
+# Validate the final region
+ibmcloud regions | grep -w "$IC_REGION" > /dev/null || {
+   echo -e "Error: Invalid region \"$IC_REGION\"!!!" >> $E2E_TEST_SETUP
+   exit 1
+}
+
 ibmcloud target -r "$IC_REGION"
 
+# Resolve KS API endpoint
 if [[ -n "$E2ETEST_CS_API_EP" ]]; then
-   ibmcloud ks init --host $E2ETEST_CS_API_EP
+    KS_HOST="$E2ETEST_CS_API_EP"
+elif [[ "$e2e_env" == "stage" || "$e2e_env" == "stage-us-south" ]]; then
+    KS_HOST="https://containers.test.cloud.ibm.com"
 else
-   ibmcloud ks init --host https://containers.cloud.ibm.com
+    KS_HOST="https://containers.cloud.ibm.com"
 fi
+
+if [[ -z "$KS_HOST" ]]; then
+    echo "ERROR: KS_HOST is empty" >> $E2E_TEST_SETUP
+    exit 1
+fi
+
+echo "KS endpoint : $KS_HOST"
+ibmcloud ks init --host "$KS_HOST"
 
 if [[ $IC_PROVIDER == "vpc-gen2" ]] ; then
    ibmcloud is target --gen 2
