Add EIT e2e cases (#33)
* Add EIT test cases

* Increase sleep

* update comment

* updates

* Fix negative use case

* Remove test file

* Rmeove ginkgo tag

* Add ibmcloud binary

* fix issue with iks-cluster script

* review comments

* ibmcloud linux build

* update binary

* temp: enable operator addon via curl

* temp: Enable outbound access for 1.30

* improvements

* improvements

* test failing test cases

* Fix MZ input

* revert

* Fix cluster issues

* Source iks-cluster variable in e2e.sh

* diff

* Fix for negative use case

* Fix eit use cases

* Use icr.io image

* Use vpc-file in cluster name prefix

* Fix format issues

* update image + sc name

* Update image to network team recommendation

* Run eit test cases only when flag passed is true

Signed-off-by: Prankul <84079249+prankulmahajan@users.noreply.github.com>

* Add sc based on addon version

Signed-off-by: Prankul <84079249+prankulmahajan@users.noreply.github.com>

* Handle old VolumeIDSeperator

---------

Signed-off-by: Prankul <84079249+prankulmahajan@users.noreply.github.com>

diff --git a/e2e/iks-cluster b/e2e/iks-cluster
--- a/e2e/iks-cluster
+++ b/e2e/iks-cluster
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Licensed Materials - Property of IBM
 #
-# (C) Copyright IBM Corp. 2021 All Rights Reserved
+# (C) Copyright IBM Corp. 2024 All Rights Reserved
 #
 # US Government Users Restricted Rights - Use, duplicate or
 # disclosure restricted by GSA ADP Schedule Contract with
@@ -70,7 +70,7 @@ PLATFORM_openshift="ocp"
 PRIMARY_ZONE_ID="01"	# ZONE_vpc_gen2_01 / ZONE_classic_01
 SECOND_ZONE_ID="03"	# ZONE_vpc_gen2_03 / ZONE_classic_03
 
-CLUSTER_NAME_SUFFIX="e2etest"
+CLUSTER_NAME_SUFFIX="vpc-file-e2etest"
 
 function exportKubeConfig {
     if [[ $# -ne 1 ]]; then
@@ -377,6 +377,11 @@ function cluster_create_vpc {
     if [[ "$E2ETEST_MZ" == "true" && "$K8S_PLATFORM" != "openshift" ]]; then
        worker_node_count=$WORKER_NODE_COUNT_PERZONE
     fi
+
+    version_ge() {
+        [ "$(printf '%s\n' "$1" "$2" | sort -V | head -n1)" = "$2" ]
+    }
+
     if [[ "$K8S_PLATFORM" == "openshift" ]]; then
         # OpenShift minimum 2 worker nodes are required
         worker_node_count=$WORKER_NODE_COUNT
@@ -385,19 +390,34 @@ function cluster_create_vpc {
         else
             E2ETEST_IC_COS_INSTANCE=$(ibmcloud resource service-instance "Cloud Object Storage-rz"  | grep "^ID:" | awk '{print $2}')
         fi
-        ibmcloud ks cluster create $IC_PROVIDER --name $cluster_name --zone $PRIMARY_ZONE \
+        # Disable outbound traffic protection in case EIT test cases are to be executed
+        if [[ "$e2e_eit_test_case" == "true" ]] && version_ge "$kube_ver" "4.16.0" && version_ge "$e2e_addon_version" "2.0"; then
+            ibmcloud ks cluster create $IC_PROVIDER --name $cluster_name --zone $PRIMARY_ZONE \
             --vpc-id $VPC_ID --subnet-id $PRIM_SUBNET_ID --version $kube_ver --cos-instance "$E2ETEST_IC_COS_INSTANCE" \
-	    --flavor $WORKER_NODE_FLAVOR --workers $worker_node_count; rc=$?
+            --flavor $WORKER_NODE_FLAVOR --workers $worker_node_count --disable-outbound-traffic-protection; rc=$?
+        else
+            ibmcloud ks cluster create $IC_PROVIDER --name $cluster_name --zone $PRIMARY_ZONE \
+            --vpc-id $VPC_ID --subnet-id $PRIM_SUBNET_ID --version $kube_ver --cos-instance "$E2ETEST_IC_COS_INSTANCE" \
+            --flavor $WORKER_NODE_FLAVOR --workers $worker_node_count; rc=$?
+        fi
     else
-        ibmcloud ks cluster create $IC_PROVIDER --name $cluster_name --zone $PRIMARY_ZONE \
+        # Disable outbound traffic protection in case EIT test cases are to be executed
+        if [[ "$e2e_eit_test_case" == "true" ]] && version_ge "$kube_ver" "1.30.0" && version_ge "$e2e_addon_version" "2.0"; then
+            ibmcloud ks cluster create $IC_PROVIDER --name $cluster_name --zone $PRIMARY_ZONE \
             --vpc-id $VPC_ID --subnet-id $PRIM_SUBNET_ID --version $kube_ver \
-	    --flavor $WORKER_NODE_FLAVOR --workers $worker_node_count; rc=$?
+            --flavor $WORKER_NODE_FLAVOR --workers $worker_node_count --disable-outbound-traffic-protection; rc=$?
+        else
+            ibmcloud ks cluster create $IC_PROVIDER --name $cluster_name --zone $PRIMARY_ZONE \
+            --vpc-id $VPC_ID --subnet-id $PRIM_SUBNET_ID --version $kube_ver \
+            --flavor $WORKER_NODE_FLAVOR --workers $worker_node_count; rc=$?
+        fi
     fi
     if [[ $rc -ne 0 ]]; then set +x;  return 1; fi
 
     if [[ $E2ETEST_MZ == "true" ]]; then
-	random_string=${cluster_name%%-*}
+        random_string=${cluster_name%%-*}
         cluster_worker_pool="e2etest-${random_string}"
+        echo "cluster_worker_pool=\"$cluster_worker_pool\"" > /tmp/e2e_vars.sh
         ibmcloud ks worker-pool create $IC_PROVIDER --name ${cluster_worker_pool} --cluster $cluster_name \
           --flavor $WORKER_NODE_FLAVOR --vpc-id $VPC_ID --size-per-zone $WORKER_NODE_COUNT_PERZONE; rc=$?
         if [[ $rc -ne 0 ]]; then set +x;  return 1; fi
@@ -533,6 +553,35 @@ function check_worker_state {
     return 0
 }
 
+function check_storage_operator_addon {
+    if [[ $# -ne 2 ]]; then
+        echo "${FUNCNAME[0]}: Invalid parameters. Provide cluster name and addon version"
+        return 1
+    fi
+
+    cluster_name="$1"
+    addon_version="$2"
+
+    sudo apt-get install bc -y
+
+    # Operator should not be installed for vpc file addon versions <2.0
+    if [[ $(echo "$addon_version < 2.0" | bc -l) -eq 1 ]]; then
+        echo "Addon version $addon_version does not require storage operator"
+        return 0
+    fi
+
+    # Operator is installed by default on all IKS/ROKS cluster.
+    addon_present=$(ibmcloud ks cluster addon ls -c $cluster_name -q | grep ibm-storage-operator)
+    if [[ $addon_present != "" ]]; then
+        echo "Storage operator already enabled on the cluster"
+    else
+        # If not present enable ibm-storage-operator. This command will fail if kube version is <IKS1.30 or <ROKS4.15
+        ibmcloud ks cluster addon enable ibm-storage-operator -c $cluster_name
+    fi
+
+    sleep 30
+    return 0
+}
 
 function delete_cluster {
     if [[ $# -ne 1 ]]; then
@@ -628,12 +677,13 @@ e2e_mz="false"
 e2e_var_exports=""
 e2e_name_tag=""
 e2e_addon_update="false"
+e2e_eit_test_case="false"
 
 cmd_name="$0"
 usage_str="$cmd_name: Options:-
         -e <prod|stage> -d <cluster name> or
         -e <prod|stage> -c <exiting cluster name> or
-        -e <prod|stage> --fresh [-n <name tag> ] -k default|latest|base -p classic|vpc-gen2 -t k8s|ocp -r <region> [--mz] [--retain]"
+        -e <prod|stage> --fresh [-n <name tag> ] -k default|latest|base -p classic|vpc-gen2 -t k8s|ocp -r <region> [--mz] [--retain] [--run-eit-test-cases]"
 
 if [[ $# -lt 1 ]]; then
 	echo "$usage_str"
@@ -725,6 +775,12 @@ key="$1"
 	e2e_addon_update="true"
 	shift
 	;;
+
+    --run-eit-test-cases)
+    e2e_eit_test_case="$2"
+    shift
+    shift
+    ;;
 
 	--exports)
 	e2e_var_exports="$2"
@@ -1060,7 +1116,11 @@ exportKubeConfig $cluster_name; rc=$?
 # From Jenkins there is option to mention addon version and by default FILE CSI driver is not enabled
 # Enable user specified version
 
-ibmcloud ks cluster addon enable vpc-file-csi-driver --cluster $cluster_name --version $e2e_addon_version
+# Check if storage operator needs to be enabled
+check_storage_operator_addon $cluster_name $e2e_addon_version
+
+# Enable file csi driver
+ibmcloud ks cluster addon enable vpc-file-csi-driver --version $e2e_addon_version --cluster $cluster_name
 sleep 30
 check_addon_pod_status ibm-vpc-file-csi-controller
 
